pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/sultanelmolla/ksa-demo.git'
            }
        }

        stage('Build') {
            steps {
                echo '✅ Build step (no compilation needed for HTML)'
            }
        }

        stage('Run') {
            steps {
                echo '🚀 Opening HTML file...'
                bat 'start ksa.html'
            }
        }
    }
}
